//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Code.PlayerInput
{
    public partial class @InputControls: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input Controls"",
    ""maps"": [
        {
            ""name"": ""Level"",
            ""id"": ""1abeea9c-6108-4915-9e65-c485724fca3e"",
            ""actions"": [
                {
                    ""name"": ""LMB"",
                    ""type"": ""Button"",
                    ""id"": ""74b08d0f-954d-4b4e-8aab-1184dd349bc6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""312cb1b9-e56f-42ef-a79a-59f682b858f8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";mouse and keyboard"",
                    ""action"": ""LMB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""mouse and keyboard"",
            ""bindingGroup"": ""mouse and keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Level
            m_Level = asset.FindActionMap("Level", throwIfNotFound: true);
            m_Level_LMB = m_Level.FindAction("LMB", throwIfNotFound: true);
        }

        ~@InputControls()
        {
            UnityEngine.Debug.Assert(!m_Level.enabled, "This will cause a leak and performance issues, InputControls.Level.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Level
        private readonly InputActionMap m_Level;
        private List<ILevelActions> m_LevelActionsCallbackInterfaces = new List<ILevelActions>();
        private readonly InputAction m_Level_LMB;
        public struct LevelActions
        {
            private @InputControls m_Wrapper;
            public LevelActions(@InputControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @LMB => m_Wrapper.m_Level_LMB;
            public InputActionMap Get() { return m_Wrapper.m_Level; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(LevelActions set) { return set.Get(); }
            public void AddCallbacks(ILevelActions instance)
            {
                if (instance == null || m_Wrapper.m_LevelActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_LevelActionsCallbackInterfaces.Add(instance);
                @LMB.started += instance.OnLMB;
                @LMB.performed += instance.OnLMB;
                @LMB.canceled += instance.OnLMB;
            }

            private void UnregisterCallbacks(ILevelActions instance)
            {
                @LMB.started -= instance.OnLMB;
                @LMB.performed -= instance.OnLMB;
                @LMB.canceled -= instance.OnLMB;
            }

            public void RemoveCallbacks(ILevelActions instance)
            {
                if (m_Wrapper.m_LevelActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ILevelActions instance)
            {
                foreach (var item in m_Wrapper.m_LevelActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_LevelActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public LevelActions @Level => new LevelActions(this);
        private int m_mouseandkeyboardSchemeIndex = -1;
        public InputControlScheme mouseandkeyboardScheme
        {
            get
            {
                if (m_mouseandkeyboardSchemeIndex == -1) m_mouseandkeyboardSchemeIndex = asset.FindControlSchemeIndex("mouse and keyboard");
                return asset.controlSchemes[m_mouseandkeyboardSchemeIndex];
            }
        }
        public interface ILevelActions
        {
            void OnLMB(InputAction.CallbackContext context);
        }
    }
}
